/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.authdb.tables;


import com.example.jooq.authdb.Authdb;
import com.example.jooq.authdb.Indexes;
import com.example.jooq.authdb.Keys;

import java.time.Instant;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.AutoConverter;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AuthUsers extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>authdb.auth_users</code>
     */
    public static final AuthUsers AUTH_USERS = new AuthUsers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>authdb.auth_users.id</code>.
     */
    public final TableField<Record, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>authdb.auth_users.email</code>.
     */
    public final TableField<Record, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>authdb.auth_users.password</code>.
     */
    public final TableField<Record, String> PASSWORD = createField(DSL.name("password"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>authdb.auth_users.created_at</code>.
     */
    public final TableField<Record, Instant> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "", new AutoConverter<LocalDateTime, Instant>(LocalDateTime.class, Instant.class));

    /**
     * The column <code>authdb.auth_users.updated_at</code>.
     */
    public final TableField<Record, Instant> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "", new AutoConverter<LocalDateTime, Instant>(LocalDateTime.class, Instant.class));

    /**
     * The column <code>authdb.auth_users.role</code>.
     */
    public final TableField<Record, String> ROLE = createField(DSL.name("role"), SQLDataType.VARCHAR(10).nullable(false).defaultValue(DSL.inline("USER", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>authdb.auth_users.user_id</code>.
     */
    public final TableField<Record, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>authdb.auth_users.uuid</code>.
     */
    public final TableField<Record, Long> UUID = createField(DSL.name("uuid"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    private AuthUsers(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AuthUsers(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>authdb.auth_users</code> table reference
     */
    public AuthUsers(String alias) {
        this(DSL.name(alias), AUTH_USERS);
    }

    /**
     * Create an aliased <code>authdb.auth_users</code> table reference
     */
    public AuthUsers(Name alias) {
        this(alias, AUTH_USERS);
    }

    /**
     * Create a <code>authdb.auth_users</code> table reference
     */
    public AuthUsers() {
        this(DSL.name("auth_users"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Authdb.AUTHDB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.AUTH_USERS_IDX_AUTH_USERS_EMAIL);
    }

    @Override
    public Identity<Record, Integer> getIdentity() {
        return (Identity<Record, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.KEY_AUTH_USERS_PRIMARY;
    }

    @Override
    public List<UniqueKey<Record>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_AUTH_USERS_EMAIL, Keys.KEY_AUTH_USERS_UK_USER_ID, Keys.KEY_AUTH_USERS_UK_UUID);
    }

    @Override
    public AuthUsers as(String alias) {
        return new AuthUsers(DSL.name(alias), this);
    }

    @Override
    public AuthUsers as(Name alias) {
        return new AuthUsers(alias, this);
    }

    @Override
    public AuthUsers as(Table<?> alias) {
        return new AuthUsers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthUsers rename(String name) {
        return new AuthUsers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthUsers rename(Name name) {
        return new AuthUsers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthUsers rename(Table<?> name) {
        return new AuthUsers(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthUsers where(Condition condition) {
        return new AuthUsers(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthUsers where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthUsers where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthUsers where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthUsers where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthUsers where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthUsers where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthUsers where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthUsers whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthUsers whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
