/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.authdb;


import com.example.jooq.DefaultCatalog;
import com.example.jooq.authdb.tables.AuthUsers;
import com.example.jooq.authdb.tables.Tokens;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Authdb extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>authdb</code>
     */
    public static final Authdb AUTHDB = new Authdb();

    /**
     * The table <code>authdb.auth_users</code>.
     */
    public final AuthUsers AUTH_USERS = AuthUsers.AUTH_USERS;

    /**
     * The table <code>authdb.tokens</code>.
     */
    public final Tokens TOKENS = Tokens.TOKENS;

    /**
     * No further instances allowed
     */
    private Authdb() {
        super("authdb", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AuthUsers.AUTH_USERS,
            Tokens.TOKENS
        );
    }
}
