/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.authdb;


import com.example.jooq.authdb.tables.AuthUsers;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in authdb.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index AUTH_USERS_IDX_AUTH_USERS_EMAIL = Internal.createIndex(DSL.name("idx_auth_users_email"), AuthUsers.AUTH_USERS, new OrderField[] { AuthUsers.AUTH_USERS.EMAIL }, false);
}
