/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.authdb;


import com.example.jooq.authdb.tables.AuthUsers;
import com.example.jooq.authdb.tables.Tokens;

import org.jooq.Record;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * authdb.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<Record> KEY_AUTH_USERS_EMAIL = Internal.createUniqueKey(AuthUsers.AUTH_USERS, DSL.name("KEY_auth_users_email"), new TableField[] { AuthUsers.AUTH_USERS.EMAIL }, true);
    public static final UniqueKey<Record> KEY_AUTH_USERS_PRIMARY = Internal.createUniqueKey(AuthUsers.AUTH_USERS, DSL.name("KEY_auth_users_PRIMARY"), new TableField[] { AuthUsers.AUTH_USERS.ID }, true);
    public static final UniqueKey<Record> KEY_AUTH_USERS_UK_USER_ID = Internal.createUniqueKey(AuthUsers.AUTH_USERS, DSL.name("KEY_auth_users_uk_user_id"), new TableField[] { AuthUsers.AUTH_USERS.USER_ID }, true);
    public static final UniqueKey<Record> KEY_AUTH_USERS_UK_UUID = Internal.createUniqueKey(AuthUsers.AUTH_USERS, DSL.name("KEY_auth_users_uk_uuid"), new TableField[] { AuthUsers.AUTH_USERS.UUID }, true);
    public static final UniqueKey<Record> KEY_TOKENS_PRIMARY = Internal.createUniqueKey(Tokens.TOKENS, DSL.name("KEY_tokens_PRIMARY"), new TableField[] { Tokens.TOKENS.ID }, true);
    public static final UniqueKey<Record> KEY_TOKENS_TOKEN = Internal.createUniqueKey(Tokens.TOKENS, DSL.name("KEY_tokens_token"), new TableField[] { Tokens.TOKENS.TOKEN }, true);
}
