/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.authdb;


import com.example.jooq.authdb.tables.AuthUsers;
import com.example.jooq.authdb.tables.Tokens;


/**
 * Convenience access to all tables in authdb.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>authdb.auth_users</code>.
     */
    public static final AuthUsers AUTH_USERS = AuthUsers.AUTH_USERS;

    /**
     * The table <code>authdb.tokens</code>.
     */
    public static final Tokens TOKENS = Tokens.TOKENS;
}
